### ISSUE TITLE
Random itinerary in the middle of vignette

### ISSUE THREAD

**Issue by tarakc02** [USEPA/elevatr#10]
Sorry for the deluge, while I was fiddling with my pull request, I happened to read the vignette and noticed that there appears to have been a copy/paste accident and thought you'd probably want to know:

> Example usage of each is included below. For these examples, we can creEstimate below:
> 
> Flight:
>  $525.20 (contract fare) Car: $211.20 (need to figure out extra day that I'd be on AL) Per diem: $224.00 (Two travel days, two full days) Total: $960.40ate a dataset to use.

**Comment by jhollist** [comment]
Ha!

@tarakc02 that is really funny and a fairly accurate estimate of an upcoming trip!

Thanks for catching that.  I'll yank it out it soon.
