### ISSUE TITLE
Missing implementation of issues in currently available version 0.1.3

### ISSUE THREAD

**Issue by pascalfust** [USEPA/elevatr#2]
Dear Jeffrey,

unfortunately, the currently available version (0.1.3) of the _elevatr_ package is showing issues at the application of the get_elev_raster function within MapZen. It keeps on giving the error message "API did not return tif". 
Luckily, the code of the functions is openly accessible, so I could figure out, where the problem was. 

Firstly, in the function _get_mapzen_terrain_, the current web url is referring to https://tile.mapzen.com/mapzen/terrain/v1/geotiff, instead to the currently applicable http://tile.mapzen.com/mapzen/terrain/v1/geotiff.
Furthermore is the format check in this function checking on "**image/tif**" instead of the correct statement "**image/tiff**". 
Please could you make the corresponding corrections in the code and release a corrected version (0.1.4?) to the public, so that all users can get access to the elevation data collection of mapzen through your very useful tool in R, without the need of running their own corrected functions?

Thank you for your support and work for the R community!

Best regards,
Pascal Fust

**Comment by jhollist** [comment]
@pascalfust 

Thanks for the issue.  You are correct that the version on CRAN is not working.  A fix was incorporated on GitHub a while back so if you use
```
devtools::install_github("usepa/elevatr") 
```
It should work.  Thanks to your reminder, I will try to push this to CRAN today.
