### ISSUE TITLE
change -1000000 to NA

### ISSUE THREAD

**Issue by agricolamz** [USEPA/elevatr#24]
Hi,

as stated [here](https://ned.usgs.gov/epqs/): "If unable to find data at the requested point, this service returns -1000000". I'd propose to return `NA` in that cases, otherwise users will spent some time suffering...

**Comment by jhollist** [comment]
Thank for the catch, @agricolamz Current version in master now converts those missing values to a proper NA.

**Comment by agricolamz** [comment]
Cool, thank you!
