### ISSUE TITLE
Feature request: Global point data extraction

### ISSUE THREAD

**Issue by stineb** [USEPA/elevatr#30]
Hi there. Thank you very much for offering this package - it's very useful. If the point data extraction would be possible for points outside the US (connecting to a respective data server that offers global gtopo30 data), its usefulness would be tremendously enhanced. Or did I miss anything? Thx. b

**Comment by jhollist** [comment]
Thanks for the comment.  What you are looking for should be supported if you use the "aws" source for get_elev_points.  It essentially grabs the rasters and returns elevations for the supplied points.  You'll need to think about specifying a z value and the number of points you supply.  This is a work around.  This was originally supported by mapzen's point elevation service.  After they closed shop no one took up support for that service.

In any event if you try something like:

```
get_elev_points(points, src = "aws", z = 5) 
```

Let me know if that does the trick.

**Comment by jhollist** [comment]
@stineb I am working on clearing out some issues.  Were you able to try the "aws" src for get_elev_points on points around the globe?  I'll be closing out this issue if I don't hear back in a few weeks.
