### ISSUE TITLE
get_elev_point: Error: API did not return json

### ISSUE THREAD

**Issue by tmt2131** [USEPA/elevatr#32]
Hi!

Great package that's been really helpful. Quick question, I've used this package in the past with no problems. I tried running something new today and received this error message: "Error: API did not return json".

I tried running the sample code on this page (https://rdrr.io/cran/elevatr/man/get_elev_point.html) to see if it was my code and I'm getting the same error message. Are there any changes that I should be aware of? Thanks!

**Comment by jhollist** [comment]
Glad to hear you are finding `elevatr` helpful.

I just tested my example code for both `get_elev_raster` and `get_elev_point` and it is working for me.  

The API you were using may have been down for a bit?  Try again and if it is still not working, let me know along with the code you ran and the result of sessionInfo().

**Comment by tmt2131** [comment]
Hi Jeff,

Thanks for the quick response. Thanks for offering to help. I've tried it
several times since I've gotten your email without any success. My
understanding is that API is external to my computer and would be on the
(in this case) USGS or web side.

I used the example code here

*library(elevatr)*

*mt_wash <- data.frame(x = -71.3036, y = 44.2700)*
*mt_mans <- data.frame(x = -72.8145, y = 44.5438)*
*mts <- rbind(mt_wash,mt_mans)*
*ll_prj <- "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"*
*mts_sp <- sp::SpatialPoints(sp::coordinates(mts), *
*                            proj4string = sp::CRS(ll_prj)) *
*get_elev_point(locations = mt_wash, prj = ll_prj)*
*>*Error: API did not return json
*get_elev_point(locations = mt_wash, units="feet", prj = ll_prj)*
*>*Error: API did not return json
*get_elev_point(locations = mt_wash, units="meters", src = "epqs", prj =
ll_prj)*
*>*Error: API did not return json
*get_elev_point(locations = mts_sp)*
>Error: API did not return json

Here's the print out of my sessionInfo()

*R version 3.6.3 (2020-02-29)*
*Platform: x86_64-apple-darwin15.6.0 (64-bit)*
*Running under: macOS Catalina 10.15.5*

*Matrix products: default*
*BLAS:
/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib*
*LAPACK:
/Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib*

*Random number generation:*
* RNG:     Mersenne-Twister *
* Normal:  Inversion *
* Sample:  Rounding *

*locale:*
*[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8*

*attached base packages:*
*[1] stats     graphics  grDevices utils     datasets  methods   base     *

*other attached packages:*
* [1] elevatr_0.2.1.9999 SDMTools_1.1-221.1 rgdal_1.4-8        raster_3.3-7
      maptools_0.9-9    *
* [6] sp_1.4-2           ncdf4_1.17         textreg_0.1.5
 stringr_1.4.0      tibble_3.0.1      *
*[11] tm_0.7-7           NLP_0.2-0          data.table_1.12.8 *

*loaded via a namespace (and not attached):*
* [1] Rcpp_1.0.4.6      pillar_1.4.3      compiler_3.6.3
 prettyunits_1.1.1 progress_1.2.2    R.methodsS3_1.8.0*
* [7] R.utils_2.9.2     tools_3.6.3       lifecycle_0.2.0   lattice_0.20-38
  pkgconfig_2.0.3   rlang_0.4.6      *
*[13] cli_2.0.2         rstudioapi_0.11   curl_4.3          parallel_3.6.3
   xfun_0.13         httr_1.4.1       *
*[19] xml2_1.3.2        knitr_1.28        hms_0.5.3         vctrs_0.3.1
  grid_3.6.3        glue_1.4.1       *
*[25] R6_2.4.1          fansi_0.4.1       foreign_0.8-75    magrittr_1.5
   codetools_0.2-16  ellipsis_0.3.1   *
*[31] assertthat_0.2.1  stringi_1.4.6     slam_0.1-47       crayon_1.3.4
   R.oo_1.23.0      *

I also tried running all of this on my lab's server since I wasn't quite
sure if I understood API correctly and received the same error message.

Thanks for your help!

Tammy

**Comment by jhollist** [comment]
@tmt2131 So, it appears to be a server side issue.  The USGS server returns a 503 error.  While I was testing it, it worked, then it didn't...  On the epqs site there is a message about maintenance, so that is likely the issue.  It should resolve itself at some point.

Alternatively, you can use the "aws" source with a resonably high z value.

Something like:

```
get_elev_point(locations = mt_wash, prj = ll_prj, src = "aws", z = 12)
```

should work.  Depending on number of points and how close those points are, this can take some time.  I think at this point, I am  fairly sure this is not an `elevatr` issue.  I'm going to close the issue, but if you continue to have problems in a few days, feel free to re-open the issue.

Thanks!

**Comment by jhollist** [comment]
Never mind, I am going to reopen this.

It is a server side issue  because the have changed to service URL!   I need to look into this some more.  

If the aws source works for you, use that for now.  I am not entirely sure when I will have time to get at this fix.

**Comment by tmt2131** [comment]
Hi Jeffrey,

Thanks for looking into this and keeping the issue open. I tried inputting
the values directly into USGS’s point inquiry website earlier today, before
emailing you, and it had worked directly on the website. Thanks for
communicating the issue and the problem. Unfortunately, aws source won’t
work but I’ll find another solution in the meantime. Thanks again for your
help!

Best,
Tammy
