### ISSUE TITLE
Mosaic/Projection Speed up

### ISSUE THREAD

**Issue by mikejohnson51** [USEPA/elevatr#33]
Hi Jeff, 

I really enjoy `elevatr` and use it **a lot** in my research! 

As I am scaling up my analysis, I find the merging of rasters to be a bottle neck. I hacked together a solution (not yet ready to make a nice reprex.. so sorry for the screen shot!)

![image](https://user-images.githubusercontent.com/30052272/87073038-9af08100-c1d1-11ea-97c4-9f0eb1d57708.png)

If you are interested, I can move this forward as a pull request - but I wanted to gage your interest before deciding how "formal" to make this...

It shouldn't add any dependencies to your package.

Either way, thanks for all the great work you do,

Mike

**Comment by jhollist** [comment]
Thanks a lot for the comments.  I am always thrilled to hear that people are finding elevatr useful.  Be curious to hear about your research and what you are using it for. 

And as far as the speed up, that is a nice improvement.  I would be happy to consider a PR with this in it.  And I am interested to see what you did to get this.  

Thanks again!

**Comment by mikejohnson51** [comment]
Awesome! I submitted a PR with this in it.

Much of my work is related to the on-going efforts with the National Water Model and the terrain based flood mapping (obviously your package is super for this!)

Thanks for the opportunity to contribute and hope it is useful!

Mike
