### ISSUE TITLE
get_elev_point error

### ISSUE THREAD

**Issue by SofiaAldabet** [USEPA/elevatr#39]
Hi!

I'm quite new in spatial analysis in R so sorry if this a silly issue. I'm trying to use elevatr to extract elevation from the EPQS for a SpatialPointsDataFrame, but I always get the error "Error in sp::CRS(ll_prj): PROJ4 argument-value pairs must begin with +". I even tried using your example in https://cran.r-project.org/web/packages/elevatr/vignettes/introduction_to_elevatr.html#Get_Point_Elevation_Data, but I get the same error. What can I do?

Thanks!!

**Comment by lisamr** [comment]
Hi, I'm also running into the same issue when I try to follow along with the vignette linked above: 

I get the same error above when I try to extract elevation point data, as well as raster data. Here is the error with `get_elev_raster`:
`> elevation_df <- get_elev_raster(examp_df, prj = prj_dd, z = 5)`  
`Error in sp::spTransform(locations, sp::CRS("+init=EPSG:4326")) : 
 No transformation possible from NA reference system
In addition: Warning message:
In sp::CRS(prj) : CRS: projargs should not be NULL; set to NA`

**Comment by jhollist** [comment]
Sorry for the issues.  I am still trying to wrap my head around all the PROJ related changes.  I have a fix (plus some other stuff) that should be up on CRAN next week.  The dev version here has all of those changes and and updated vignette (in Rmd) is at https://github.com/jhollist/elevatr/blob/main/vignettes/introduction_to_elevatr.Rmd

I'll be sure to let you both know here when I get the changes pushed to CRAN.

And thanks for reporting these problems!!

**Comment by jhollist** [comment]
Going to close this.  I think all the changes that dealt with this are on CRAN now.  Any other issues arrive, please do let me know.
