### ISSUE TITLE
Struggling to get `get_elev_point` to work

### ISSUE THREAD

**Issue by barnettjacob** [USEPA/elevatr#5]
Hi Jeff, struggling to get it working! Any ideas based on the below?
Cheers
Jacob

### My data:
![image](https://cloud.githubusercontent.com/assets/7270997/20174531/268eb0c0-a736-11e6-9474-24e8641e3a37.png)

### The code
```
#set the prj thing
ll_prj <- "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"

#get_elevations
elevations <- get_elev_point(data, ll_prj)
```

### From the debugger
![image](https://cloud.githubusercontent.com/assets/7270997/20174106/3a4591ee-a734-11e6-89b1-00f55e9d9ea7.png)

**Comment by jhollist** [comment]
Thanks, @barnettjacob!

Oops.  Looks like I left a browser() in there!  Will get to that later this AM.

**Comment by barnettjacob** [comment]
Ah - shown up by my lack of knowledge on how R debugging works! Cheers.

**Comment by jhollist** [comment]
@barnettjacob No problem.  It was a good catch!

Should be good now.  Go ahead and reinstall and give it a shot.  

Also, if you have lots of points, it will probably error as mapzen limits number of requests.  I'm going to work on making that work a bit smoother, but it isn't there yet!

Thanks again for finding this and for using the package!

**Comment by barnettjacob** [comment]
Thanks! Now working!!
