### ISSUE TITLE
Return strange results

### ISSUE THREAD

**Issue by arielfuentes** [USEPA/elevatr#55]
I extracted elevation data but while using aws as source, the output data is somehow incoherent, I'm wondering if I did something wrong or the problem is the dem.  The code that I used was:

````pts1 <- data.frame(
  X1 = c(-70.4077158383982,-70.3935393109716,
         -70.3949681297638,-70.3972246855408,-70.4019095866058,
         -70.3826509943981,-70.4022484382468,-70.388213981289,-70.4036039310082),
  X2 = c(-23.6747478404244,-23.6487958738395,
         -23.6502443366449,-23.6521063660703,-23.662803808573,
         -23.5670705593215,-23.6634749725216,-23.6140268217696,-23.666165326631)
)
pts1 <- SpatialPoints(coordinates(pts1), 
                      proj4string = CRS("EPSG:4326"))

res <- get_elev_point(pts1, src = "aws")````

**Comment by jhollist** [comment]
@arielfuentes I see you closed this.  I assume you were able to track down the issue on your own?  If you are still having problems, let me know and I can take a look.

Thanks!

**Comment by arielfuentes** [comment]
I thought I made I mistake but apparently, I didn't. Instead of using **get_elev_points** I used **get_elev_raster** and after that **raster::extract** and then it returned the right output. It seems there is an issue but I will reopen it when I have the time to create a reproducible example to show you this. And I'm really grateful for your help.

**Comment by arielfuentes** [comment]
@jhollist in the following code I show two ways to get elevation data, why is the output different?

```library(sf)
library(raster)
data(meuse)
meuse <- st_as_sf(meuse, coords = c("x", "y"), crs = 28992) %>%
  st_transform(4326) %>%
  as_Spatial()

meuse_elev1 <- get_elev_point(meuse, src = "aws")
#output1
meuse_elev1$elev

dem <- get_elev_raster(meuse, z = 14)
#output2
meuse_elev2 <- extract(dem, meuse)
```
Thank you in advance!

**Comment by jhollist** [comment]
@arielfuentes sorry for delay in getting to this.  There are two things going on here.  First, the "elev" is from the meuse dataset and not from elevatr.  Not sure what elevation it is measuring or what units it is supposed to be in.  The "elevation" column is the elevation that comes from elevatr.  So if you look at `meuse_elev1$elevation` then the numbers look similar, but not quite.  

This second issue is that the default z value when using the "aws" source is pretty coarse.  If you match that to what you used with get_elev_raster then the numbers are a very close match (within rounding error).

So, if you use

```
meuse_elev1 <- get_elev_point(meuse, src = "aws", z = 14)
#output1
meuse_elev1$elevation

dem <- get_elev_raster(meuse, z = 14)
#output2
meuse_elev2 <- extract(dem, meuse)
```

Then the outputs should match.  

That answer your question?

**Comment by arielfuentes** [comment]
@jhollist Don't worry and yes this answer it, thank you.
