### ISSUE TITLE
Is there no function for extracting point data from outside the US?

### ISSUE THREAD

**Issue by kamaulindhardt** [USEPA/elevatr#74]
Is there no function for extracting elevation point data from outside the US? 

Just like you've made with `get_elev_point()` to get point elevations from the US. Or is it only raster data that is available at global scale?

**Comment by jhollist** [comment]
@kamaulindhardt You can specify "aws" as the `src` in get_elev_point and it will return point elevations from the AWS terrain tiles.  That should work globally.  It uses get_elev_raster to grab the raster and then extracts the elevations from the raster.  You will need to select an appropriation  zoom (i.e., `z`) for your application. 

Also, I don't know of any global point services like the USGS one.  There may be one, I  just haven't looked in a while.  If you know of one, submit an issue and I will add it to my list!

Let me know if this works.

**Comment by jhollist** [comment]
@kamaulindhardt were you able to get this to work?  Just trying to clean up some issues.

**Comment by jhollist** [comment]
Seems resolved.  If you still have questions about points outside the US.  Feel free to reopen.

**Comment by kamaulindhardt** [comment]
Thank you! 

Its a long time ago that this issue arose. I think I managed. Thanks for your efforts in replying. Best regards :)
