### ISSUE TITLE
Please remove dependencies on **rgdal**, **rgeos**, and/or **maptools**

### ISSUE THREAD

**Issue by rsbivand** [USEPA/elevatr#77]
This package depends on (depends, imports or suggests) **raster** and one or more of the retiring packages **rgdal**, **rgeos** or **maptools** (https://r-spatial.org/r/2022/04/12/evolution.html, https://r-spatial.org/r/2022/12/14/evolution2.html). Since **raster** `3.6.3`, all use of external FOSS library functionality has been transferred to **terra**, making the retiring packages very likely redundant. It would help greatly if you could remove dependencies on the retiring packages as soon as possible.

May relate to #64

**Comment by jhollist** [comment]
Thanks @rsbivand!  This is top of my list when I able to carve out some maintenance time.  I think I can get to it early in 2023.  Same applies to https://github.com/jhollist/lakemorpho/issues/18 and https://github.com/jhollist/quickmapr/issues/26

**Comment by rsbivand** [comment]
Status in recent check log from running under `_SP_EVOLUTION_STATUS_=2` without retiring r-spatial packages on the library path:
[00check.log](https://github.com/jhollist/elevatr/files/11139281/00check.log)
[00check.log](https://github.com/jhollist/elevatr/files/11139283/00check.log)
[00check.log](https://github.com/jhollist/elevatr/files/11139292/00check.log)

**Comment by rsbivand** [comment]
Please also see https://r-spatial.org/r/2023/04/10/evolution3.html, fix best by June, latest October 2023. https://github.com/jhollist/lakemorpho/issues/18 https://github.com/jhollist/quickmapr/issues/26

**Comment by jhollist** [comment]
FYI, working on this now...  Hope to have dev version finished up.  Will push to CRAN once I have contacted maintainers for rev depends...

**Comment by rsbivand** [comment]
`0.4.5` still has `rgdal` suggested - with `sp` `2.0-0` this is no longer needed, and `sf` is already imported, so `sp` will use `sf` instead. When `rgdal` is gone, and maybe `terra` added to `Suggests:`, this should be OK after October.

**Comment by jhollist** [comment]
Just submitted a new version to CRAN.  Made switch to sf and terra.  Current version still returns a RasterLayer, but will move towards sf and terra only in upcoming releases.  rgdal and sp no longer used.  I think I should be good for after October now.

And a quick thank you for all you have done for R Spatial!  I can't fully express how grateful I am for your contributions to the community!

**Comment by jhollist** [comment]
Version 0.99.0 is now on CRAN and should take care of these issues!
