### ISSUE TITLE
Provide S3 endpoints for terrain tiles

### ISSUE THREAD

**Issue by jflasher** [USEPA/elevatr#8]
From https://mapzen.com/documentation/terrain-tiles/use-service/, the tiles are available directly on S3 as well (https://aws.amazon.com/public-datasets/terrain/). Would be nice to add access directly to the tiles. You'd lose the caching provided by Mapzen's API, but you wouldn't be rate limited #4 and it'd be faster if running the code on AWS. URL is https://s3.amazonaws.com/elevation-tiles-prod/geotiff/{z}/{x}/{y}.tif.

**Comment by jhollist** [comment]
Available in current version!  Thanks for the suggestion @jflasher!

**Comment by jflasher** [comment]
😻 awesome!
