### ISSUE TITLE
USGS transferred their elevation point query service

### ISSUE THREAD

**Issue by haas4726** [USEPA/elevatr#81]
Hello,

I am attempting to run get_elev_point in a function I coded a while back.  Now, I am getting an error reading "Error: lexical error: invalid char in json text. File not found. "  I am relatively certain this is not an issue with the code (could be wrong), because it is the same code with the same test dataframe I have used in the past running the function.  I noticed the USGS moved their epqs site on March, 1.  Could this be related to that? I also tried it with src = "aws" to no avail so unsure.  Any help is appreciated, thanks!

**Comment by jhollist** [comment]
Thanks for the issue!  I do see the same error with src = "epqs".  I am able to run the examples with "aws" though.  I'll take a look at the epqs issue though.

Thanks again!

**Comment by haas4726** [comment]
Thanks! Yea I went back and looked, I had the src part of the code in the wrong place.  Was able to run it through with aws, however it seems like the USGS values were a bit more refined upon comparison.  Appreciate the support!

**Comment by jhollist** [comment]
You can try adding a z value (e.g. z=12) to get better resolution from
AWS.  But if you have a large extent for your points that may return a very
large raster.  Hope to take a look at this next week and will let you know
if I fix the USGS url issue

**Comment by jhollist** [comment]
@haas4726 This is now fixed on GitHub.  Hope to work up a submission to CRAN shortly.  Thanks for catching this!

Cheers,
Jeff
