### ISSUE TITLE
Feature suggestion: Ability to change where raster tiles are stored

### ISSUE THREAD

**Issue by andrew-caudillo** [USEPA/elevatr#95]
Hello,
This package is great and very efficient, but I would like to suggest adding the ability to declare where the temp raster tiles are stored. Some institutions, like mine, require us to store data in specific folders. Currently, elevatr does not allow this.

Thank you,

**Comment by jhollist** [comment]
@andrew-caudillo Turns out this was a pretty quick to track down.  The current version on the main branch has this ability.  Just specify a location for tmp_dir in get_elev_raster.  The location needs to already exist as I don't create a new directory.

Let me know if this works as you had hoped for!  Thanks for the suggestion.

**Comment by andrew-caudillo** [comment]
Thanks for looking into this, Jeff! I did this:
get_elev_raster(mypolygon, tmp_dir = my//special//directory, z=12) and it did not save to my//special//directory. Did I use the correct syntax?

**Comment by jhollist** [comment]
Hmmm...  Let me take another look.  I tested it with tmp_dir = "." and that did the trick.  All my unit tests assume tempfile() is used.

**Comment by jhollist** [comment]
I am able to specify any path and it works.  Make sure you have the latest version from github (will be 1.0.0.9999).  It may be still seeing the older version you had from CRAN.

**Comment by andrew-caudillo** [comment]
Thanks, Jeff- I will look into that! That is probably the reason, I do not have that version

**Comment by jhollist** [comment]
Yep!  remotes::install_github("jhollist/elevatr") will get the new one, and then just make sure you start with a fresh R session.
